# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsDropShadowEffect


class UiLoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("Login_Form")
        LoginWindow.setEnabled(True)
        LoginWindow.resize(411, 300)
        LoginWindow.setMinimumSize(QtCore.QSize(411, 300))
        LoginWindow.setMaximumSize(QtCore.QSize(411, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWindow.sizePolicy().hasHeightForWidth())
        LoginWindow.setSizePolicy(sizePolicy)
        LoginWindow.setStyleSheet("@import url(\'https://fonts.googleapis.com/css2?family=Koulen&display=swap\');\n"
"\n"
"QDialog{ \n"
"background-color: #dedede;\n"
"font-family: \'Koulen\', cursive;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    width: 100%;\n"
"    height: 20px;\n"
"    padding: 3px;\n"
"    color: #212529;\n"
"    background-color: #fff;\n"
"    background-clip: padding-box;\n"
"    border: 1px solid #dedede;\n"
"    border-radius: 3px;\n"
"    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;\n"
"}\n"
"QLineEdit::placeholder {\n"
"    color: #212529;\n"
"    opacity: 0.4;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color: #212529;\n"
"    background-color: #fff;\n"
"    border-color: #aaaaaa;\n"
"    outline: 0;\n"
"    box-shadow: 0 0 0 0.2rem rgba(158, 158, 158, 0.25);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 1px solid;\n"
"    padding: 5px;\n"
"    margin: 0px 30px;\n"
"    border-radius: 3px;\n"
"    border-color: #b5b5b5;\n"
"    background-color: #b5b5b5;\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 3px;\n"
"    border-color: #a5a5a5;\n"
"    background-color: #a5a5a5;\n"
"}\n"
"")
        self.layoutWidget = QtWidgets.QWidget(LoginWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 1, 151, 227))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.logo_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.logo_label.setFont(font)
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.gridLayout.addWidget(self.logo_label, 1, 0, 1, 1)
        self.Login_Button = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_Button.sizePolicy().hasHeightForWidth())
        self.Login_Button.setSizePolicy(sizePolicy)
        self.Login_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Login_Button.setStyleSheet("")
        self.Login_Button.setObjectName("Login_Button")
        self.gridLayout.addWidget(self.Login_Button, 6, 0, 1, 1)
        self.Login_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_LineEdit.sizePolicy().hasHeightForWidth())
        self.Login_LineEdit.setSizePolicy(sizePolicy)
        self.Login_LineEdit.setText("")
        self.Login_LineEdit.setObjectName("Login_LineEdit")
        self.gridLayout.addWidget(self.Login_LineEdit, 3, 0, 1, 1)
        self.IMAP_key_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IMAP_key_LineEdit.sizePolicy().hasHeightForWidth())
        self.IMAP_key_LineEdit.setSizePolicy(sizePolicy)
        self.IMAP_key_LineEdit.setText("")
        self.IMAP_key_LineEdit.setObjectName("IMAP_key_LineEdit")
        self.gridLayout.addWidget(self.IMAP_key_LineEdit, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.shadow_label = QtWidgets.QLabel(LoginWindow)
        self.shadow_label.setGeometry(QtCore.QRect(120, -15, 171, 250))
        self.shadow_label.setStyleSheet("background-color: #c9c9c9;\n"
"border: 1px solid;\n"
"border-color: transparent;\n"
"border-radius: 5px;")
        self.shadow_label.setText("")
        self.shadow_label.setObjectName("shadow_label")
        # set shadow
        shadow = QGraphicsDropShadowEffect()
        shadow.setBlurRadius(20)
        self.shadow_label.setGraphicsEffect(shadow)

        self.label = QtWidgets.QLabel(LoginWindow)
        self.label.setGeometry(QtCore.QRect(0, 260, 411, 41))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1.5, stop:0 #dedede, stop:1 #b5b5b5);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.shadow_label.raise_()
        self.layoutWidget.raise_()
        self.label.raise_()

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("Login_Form", "Login"))
        self.logo_label.setText(_translate("Login_Form", "Mailovy"))
        self.Login_Button.setText(_translate("Login_Form", "Login"))
        self.Login_LineEdit.setPlaceholderText(_translate("Login_Form", "Login"))
        self.IMAP_key_LineEdit.setPlaceholderText(_translate("Login_Form", "IMAP key"))
