# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsDropShadowEffect


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 677)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 677))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 677))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setStyleSheet("@import url(\'https://fonts.googleapis.com/css2?family=Koulen&display=swap\');\n"
                                 "\n"
                                 "QMainWindow{ background-color: #dedede ;}\n"
                                 "\n"
                                 "QRadioButton{padding: 2px 2px 2px 2px;\n"
                                 "spacing: 26px;"
                                 "                        margin: 1px 0px 5.2px 20px;\n"
                                 "                        border-radius: 10px;\n"
                                 "                        font-family: \'Koulen\', cursive;}\n"
                                 "\n"
                                 "QRadioButton:hover {    border-color: #b5b5b5;\n"
                                 "                        background-color: #b5b5b5;\n"
                                 "                        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c9c9c9, stop:1 #b5b5b5);\n"
                                 "}\n"
                                 "\n"
                                 "QLabel{font-family: \'Koulen\', cursive;}\n"
                                 "\n"
                                 "QPushButton{\n"
                                 "background-color: transparent;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {    border-color: #b5b5b5;\n"
                                 "                                    border-radius: 4px;\n"
                                 "                                    background-color: #b5b5b5;}\n"
                                 "\n"
                                 "\n"
                                 "\n"
                                 "")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(240, 111, 741, 521))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.messages_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.messages_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.messages_verticalLayout.setObjectName("messages_verticalLayout")


        self.right_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.right_pushButton.setGeometry(QtCore.QRect(955, 69, 28, 28))
        self.right_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.right_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/images/chevron_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right_pushButton.setIcon(icon)
        self.right_pushButton.setObjectName("right_pushButton")
        self.left_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.left_pushButton.setGeometry(QtCore.QRect(861, 69, 28, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_pushButton.sizePolicy().hasHeightForWidth())
        self.left_pushButton.setSizePolicy(sizePolicy)
        self.left_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.left_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data/images/chevron_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_pushButton.setIcon(icon1)
        self.left_pushButton.setObjectName("left_pushButton")
        self.page_label = QtWidgets.QLabel(self.centralwidget)
        self.page_label.setGeometry(QtCore.QRect(891, 69, 61, 28))
        font = QtGui.QFont()
        font.setFamily("Koulen,cursive")
        self.page_label.setFont(font)
        self.page_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.page_label.setAlignment(QtCore.Qt.AlignCenter)
        self.page_label.setObjectName("page_label")
        self.messages_label = QtWidgets.QLabel(self.centralwidget)
        self.messages_label.setGeometry(QtCore.QRect(242, 69, 71, 33))
        font = QtGui.QFont()
        font.setFamily("Koulen,cursive")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.messages_label.setFont(font)
        self.messages_label.setObjectName("messages_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-41, 111, 242, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")


        self.mailbox_label = QtWidgets.QLabel(self.centralwidget)
        self.mailbox_label.setGeometry(QtCore.QRect(20, 70, 150, 33))
        font = QtGui.QFont()
        font.setFamily("Koulen,cursive")
        font.setPointSize(12)
        self.mailbox_label.setFont(font)
        self.mailbox_label.setObjectName("mailbox_label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(205, 70, 30, 570))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(225, 100, 767, 5))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(5, 100, 210, 5))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gradient_top_label = QtWidgets.QLabel(self.centralwidget)
        self.gradient_top_label.setGeometry(QtCore.QRect(0, 0, 1011, 71))
        self.gradient_top_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #b5b5b5, stop:1 #dedede);\n"
"")
        self.gradient_top_label.setText("")
        self.gradient_top_label.setObjectName("gradient_top_label")
        self.gradient_top_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.gradient_top_label_2.setGeometry(QtCore.QRect(-10, 636, 1011, 41))
        self.gradient_top_label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #dedede, stop:1 #b5b5b5);\n"
"")
        self.gradient_top_label_2.setText("")
        self.gradient_top_label_2.setObjectName("gradient_top_label_2")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(18, 14, 161, 20))
        # set shadow
        # shadow = QGraphicsDropShadowEffect()
        # shadow.setBlurRadius(20)
        # self.logo_label.setGraphicsEffect(shadow)

        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.logo_label.setFont(font)
        self.logo_label.setStyleSheet("@import url(\'https://fonts.googleapis.com/css2?family=Koulen&display=swap\');\n"
"QLabel{\n"
"font-family: \'Koulen\', cursive;\n"
"}")

        self.logo_label.setText("Mailovy")
        #self.logo_label.setPixmap(QtGui.QPixmap("data/images/mailovy_logo.png"))
        #self.logo_label.setScaledContents(True)
        self.logo_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.logo_label.setObjectName("logo_label")
        self.logout_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.logout_pushButton.setGeometry(QtCore.QRect(955, 10, 28, 28))
        self.logout_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout_pushButton.setStyleSheet("QPushButton{\n"
"border-color: transparent;\n"
"background-color: transparent;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius: 3px;\n"
"border-color: #dedede;\n"
"background-color: #dedede;\n"
"\n"
"}\n"
"\n"
"")
        self.logout_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("data/images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_pushButton.setIcon(icon2)
        self.logout_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.logout_pushButton.setObjectName("logout_pushButton")
        self.add_mail_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.add_mail_pushButton.setGeometry(QtCore.QRect(925, 10, 28, 28))
        self.add_mail_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_mail_pushButton.setStyleSheet("QPushButton{\n"
"border-color: transparent;\n"
"background-color: transparent;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius: 3px;\n"
"border-color: #dedede;\n"
"background-color: #dedede;\n"
"\n"
"}\n"
"\n"
"")
        self.add_mail_pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("data/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_mail_pushButton.setIcon(icon3)
        self.add_mail_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.add_mail_pushButton.setObjectName("download_mail_pushButton")
        self.open_mail_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_mail_pushButton.setGeometry(QtCore.QRect(895, 10, 28, 28))
        self.open_mail_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_mail_pushButton.setStyleSheet("QPushButton{\n"
"border-color: transparent;\n"
"background-color: transparent;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius: 3px;\n"
"border-color: #dedede;\n"
"background-color: #dedede;\n"
"\n"
"}\n"
"\n"
"")
        self.open_mail_pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("data/images/folder_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_mail_pushButton.setIcon(icon4)
        self.open_mail_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.open_mail_pushButton.setObjectName("open_mail_pushButton")
        self.refresh_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_pushButton.setGeometry(QtCore.QRect(831, 69, 28, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_pushButton.sizePolicy().hasHeightForWidth())
        self.refresh_pushButton.setSizePolicy(sizePolicy)
        self.refresh_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh_pushButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("data/images/sync.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_pushButton.setIcon(icon5)
        self.refresh_pushButton.setObjectName("refresh_pushButton")
        self.gradient_top_label.raise_()
        self.gradient_top_label_2.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.right_pushButton.raise_()
        self.left_pushButton.raise_()
        self.page_label.raise_()
        self.messages_label.raise_()
        self.verticalLayoutWidget.raise_()
        self.mailbox_label.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.logo_label.raise_()
        self.line_3.raise_()
        self.logout_pushButton.raise_()
        self.add_mail_pushButton.raise_()
        self.open_mail_pushButton.raise_()
        self.refresh_pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(16, 45, 960, 20))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setStyleSheet("QComboBox{ \n"
                                    "    background-color: transparent;\n"
                                    "    padding-left: 2px;\n"
                                    "    margin-top: 0px;\n"
                                    "                     }\n"
                                    "\n"
                                    "QComboBox:hover{ \n"
                                    "    background-color: #c9c9c9;\n"
                                    "    padding-left: 2px;\n"
                                    "    border: 1px solid #c9c9c9;\n"
                                    "    border-radius: 4px;\n"
                                    "    margin-top: 0px;\n"
                                    "                     }\n"
                                    "\n"
                                    "QComboBox::drop-down { \n"
                                    "    subcontrol-origin: padding; \n"
                                    "    border: 0px;\n"
                                    "    width: 1px;\n"
                                    "                     }\n"
                                    "\n"
                                    "QComboBox QAbstractItemView {\n"
                                    "    border-top: 1px solid transparent;\n"
                                    "    border-bottom: 1px solid black;\n"
                                    "    border-right: 1px solid qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:1 #dedede, stop:0 black);\n"
                                    "    border-left: 1px solid qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:1 #dedede, stop:0 black);\n"
                                    "    background-color: #c9c9c9;\n"
                                    "    selection-background-color: #b5b5b5;\n"
                                    "}\n"
                                    "")
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        font = QtGui.QFont()
        font.setFamily("Koulen, cursive")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mailovy"))

        self.page_label.setText(_translate("MainWindow", "1-10"))
        self.messages_label.setText(_translate("MainWindow", "Messages"))
        self.mailbox_label.setText(_translate("MainWindow", "Mailbox"))
